NEW-FILE-STRUCTURE/app/level/__init__.py
from flask import Blueprint

level_bp = Blueprint('level_bp', __name__, template_folder='templates', static_folder='static', url_prefix='/levels')

from . import routes

NEW-FILE-STRUCTURE/app/level/routes.py
'''
	Routes for the level module.
'''
import requests
from model import Level

from flask import render_template
from . import level_bp

@level_bp.route('/')
def levels():
	# ''' renders the level selection menu page '''
	response = requests.get("/api/levels")
	levels_data = response.json()
	levels = [Level(**level_dict) for level_dict in levels_data]
	return render_template('levels.html', levels = levels)

@level_bp.route('/<int:level>')
def level(level):
	''' renders page for a specific level '''
	return render_template('level.html', level=level)

NEW-FILE-STRUCTURE/app/level/templates/level.html
{% extends 'base.html'%}

{% block pageTitle %}
	Sprout Quest - Level {{ level }}
{% endblock %}

{% block content %}
	<div class="level">
		<h1>Level {{ level }} - Seedling</h1>

		<div class="level__grid grid">
			{% for i in range(0,9) %}
				<div class="grid__tile tile">
					<div class="tile__wrapper">
						<div class="tile__front"></div>
						<div class="tile__back">
							<img src="{{ url_for('level_bp.static', filename='icons/sprout.svg') }}" alt="icon of a sprout" class="tile__icon">
						</div>
					</div>
				</div>
			{% endfor %}
		</div>
			
		<div class="level__resources resources">
			<h2>Resources</h2>
			<div class="resources__icons">
				<div class="icon-filling-wrapper">
					<img src="{{ url_for('level_bp.static', filename='/icons/sun.svg') }}" alt="icon of a coloured sun" class="resources__icon">
					<div class="gray-icon-mask">
						<img src="{{ url_for('level_bp.static', filename='/icons/sun-gray.svg') }}" alt="icon of a grayed out sun" class="resources__icon--gray">
					</div>
				</div>
				<div class="icon-filling-wrapper">
					<img src="{{ url_for('level_bp.static', filename='/icons/water_drop.svg') }}" alt="icon of a coloured water drop" class="resources__icon">
					<div class="gray-icon-mask">
						<img src="{{ url_for('level_bp.static', filename='/icons/water_drop-gray.svg') }}" alt="icon of a grayed out water drop" class="resources__icon--gray">
					</div>
				</div>
				<div class="icon-filling-wrapper">
					<img src="{{ url_for('level_bp.static', filename='/icons/tool.svg') }}" alt="icon of a coloured agriculture truck" class="resources__icon">
					<div class="gray-icon-mask">
						<img src="{{ url_for('level_bp.static', filename='/icons/tool-gray.svg') }}" alt="icon of a grayed out agriculture truck" class="resources__icon--gray">
					</div>
				</div>
			</div>
		</div>

		<div class="level__plant plant">
			<img src="{{ url_for('level_bp.static', filename='/images/dirt.png') }}" alt="Illustration of a pile of dirt" class="plant__dirt hidden">
			<img src="{{ url_for('level_bp.static', filename='/images/growth-1.png') }}" alt="Illustration of a sprout" class="plant__growth-1 hidden">
			<img src="{{ url_for('level_bp.static', filename='/images/growth-2.png') }}" alt="Illustration of a plant" class="plant__growth-2 hidden">
			<img src="{{ url_for('level_bp.static', filename='/images/growth-3.png') }}" alt="Illustration of a flower almost in bloom" class="plant__growth-3 hidden">
			<img src="{{ url_for('level_bp.static', filename='/images/growth-4.png') }}" alt="Illustration of a sunflower" class="plant__growth-4">
		</div>

		<div class="level__footer">
			<a href="{{ url_for('level_bp.levels') }}">Back to levels</a>
		</div>

		<div class="level__end-pop-up" style="display: none;">
			<h2>Level Complete!</h2>
			<div class="navigation-buttons">
				<a href="#">
					<button type="button">Previous Level</button>
				</a>
				<a href="#">
					<button type="button">Play again</button>
				</a>

				<a href="#">
					<button type="button">Next level</button>
				</a>
			</div>
			<a href="{{ url_for('level_bp.levels') }}">See all levels</a>
		</div>

	</div>
{% endblock %}

NEW-FILE-STRUCTURE/app/level/templates/levels.html
{% extends 'base.html' %}

{% block pageTitle %}
	Sprout Quest - Level selection
{% endblock %}

{% block content %}
<div class="levels-container">
	<div class="levels-container__header">
		<h1>Select a level</h1>
		<p>Select a difficulty to start your plant memory journey</p>
	</div>

	<div class="levels-container__content">
		<div class="content__selection">
			<div class="level-selection">
				<div class="level-selection__card card">
					<img src="{{ url_for('level_bp.static', filename='/icons/sprout.svg') }}" alt="icon of a sprout" class="card__icon">
					<h3>Seedling</h3>
					<div class="card__info">
						<p>3 x 3 grid</p>
						<p>Perfect for beginners</p>
					</div>
					<a href="{{ url_for('level_bp.level', level=1) }}">
						<button type="button" class="card__button">Start</button>
					</a>
				</div>

				<div class="level-selection__card card">
					<img src="{{ url_for('level_bp.static', filename='/icons/potted_plant.svg') }}" alt="icon of a potted plant" class="card__icon">
					<h3>Growing</h3>
					<div class="card__info">
						<p>4 x 4 grid</p>
						<p>For intermidiate players</p>
					</div>
					<a href="{{ url_for('level_bp.level', level=2) }}">
						<button type="button" class="card__button">Start</button>
					</a>
				</div>
			
				<div class="level-selection__card card">
					<img src="{{ url_for('level_bp.static', filename='/icons/flower.svg') }}" alt="icon of a flower" class="card__icon">
					<h3>Mature</h3>
					<div class="card__info">
						<p>5 x 5 grid</p>
						<p>If you want a challenge</p>
					</div>
					<a href="{{ url_for('level_bp.level', level=3) }}">
						<button type="button" class="card__button">Start</button>
					</a>
				</div>
			
				<div class="level-selection__card card">
					<img src="{{ url_for('level_bp.static', filename='/icons/zen.svg') }}" alt="icon of a lotus flower" class="card__icon">
					<h3>Seedling</h3>
					<div class="card__info">
						<p>4 x 6 grid</p>
						<p>No timer, no stress</p>
					</div>
					<a href="{{ url_for('level_bp.level', level=4) }}">
						<button type="button" class="card__button">Start</button>
					</a>
				</div>
			</div>
		</div>
		<a href="{{ url_for('main_bp.home') }}"> Back to homepage</a>
	</div>
</div>
{% endblock %}